language: python
python:
  - "2.7"

services:
  - postgresql

addons:
  postgresql: "9.4"

install:
  - pip install -r requirements-group6.txt

before_script:
  - "export DISPLAY=:99.0"
  - psql -c "CREATE USER oscar WITH PASSWORD 'oscar' CREATEDB;" -U postgres
  - psql -c "ALTER USER oscar CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE oscar OWNER oscar;" -U postgres
  - python manage.py makemigrations
  - chmod +x makemigrations.sh
  - ./makemigrations.sh
  - python manage.py migrate

script:
  - python manage.py behave
  - python validate_exercices.py
  # Following tests are useless and outdated
  # - python manage.py test